apiVersion: apps/v1
kind: Deployment
metadata:
  name: voltkv
spec:
  replicas: 1
  selector:
    matchLabels:
      name: voltkv
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata: 
      labels:
        name: voltkv
    spec:
      containers:
      - name: kvbenchmarkworkload-rdy1
        image: voltdb/kvbenchmark
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: kvbenchmark-config
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File